AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CIVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: CIVPC

  CIInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CIInternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref CIVpc
      InternetGatewayId: !Ref CIInternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CIVpc
      Tags:
        - Key: Name
          Value: CIRouteTable

  Route:
    Type: AWS::EC2::Route
    DependsOn: CIInternetGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref CIInternetGateway

  subnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-1a
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref CIVpc

  subnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-1c
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref CIVpc

  SubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnetA
      RouteTableId: !Ref RouteTable

  SubnetRouteTableAssociationC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnetC
      RouteTableId: !Ref RouteTable

Outputs:
  VpcId:
    Value: !Ref CIVpc
    Export:
      Name: !Sub ${AWS::StackName}-VpcId
  SubnetAId:
    Value: !Ref subnetA
    Export:
      Name: !Sub ${AWS::StackName}-SubnetA
  SubnetCId:
    Value: !Ref subnetC
    Export:
      Name: !Sub ${AWS::StackName}-SubnetC
  